version: '3.5'
services:
  prometheus:
    image: prom/prometheus:v2.28.0
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention.size=5GB
      - --storage.tsdb.retention.time=90d
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./targets.json:/etc/prometheus/targets.json:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
    networks:
      - monitoring
    ports:
      - "9090:9090"
  snmp-exporter:
    image: prom/snmp-exporter:v0.20.0
    container_name: snmp-exporter
    restart: always
    networks:
      - monitoring
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    ports:
    - "9116:9116"

networks:
  monitoring:
    name: monitoring
