global:
  scrape_interval: 120s
  scrape_timeout: 10s
  evaluation_interval: 30s

rule_files:
  - alerts.yml
  - rules.yml

alerting:
 alertmanagers:
 - static_configs:
   - targets:
     - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'snmp'
    scrape_interval: 60s
    static_configs:
      - targets:
        - 192.168.56.10  # SNMP device.
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'snmp-file'
    scrape_interval: 60s
    file_sd_configs:
      - files:
        - targets.json
        refresh_interval: 60s
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116  # The SNMP exporter's real hostname:port.
